import type { Icon as LucideIcon } from '@lucide/svelte';
import {
	MousePointer2,
	Scissors,
	Bookmark,
	Settings,
	Magnet,
	SkipBack,
	SkipForward,
	Play,
	Pause,
	Plug,
	LayoutPanelLeft,
	Palette,
	PlugZap,
	Upload,
	Film,
	Plus,
	AudioWaveform,
	Video,
	Captions,
	ScanLine,
	SlidersHorizontal,
	Mic,
	Clapperboard,
	Search,
	Eye,
	EyeOff,
	Lock,
	Volume2,
	VolumeX,
	Clock,
	Loader,
	GitPullRequestArrow,
	Check,
	Crop,
	ListPlus,
	CornerDownLeft,
	Hand,
	FileSearch,
	FilePlus,
	History,
	Undo2,
	Redo2,
	RotateCcw,
	FolderOpen,
	Save,
	ZoomIn,
	ZoomOut,
	Trash2,
	Copy,
	ChevronDown,
	Image,
	X,
	Download,
	RefreshCw,
	TriangleAlert,
	Lightbulb,
	ExternalLink,
	Bell
} from '@lucide/svelte';

/* Keyed by the names the design uses (kebab or PascalCase, as authored). */
export const icons: Record<string, typeof LucideIcon> = {
	'MousePointer2': MousePointer2,
	'Scissors': Scissors,
	'bookmark': Bookmark,
	'magnet': Magnet,
	'skip-back': SkipBack,
	'skip-forward': SkipForward,
	'play': Play,
	'pause': Pause,
	'plug': Plug,
	'layout-panel-left': LayoutPanelLeft,
	'palette': Palette,
	'plug-zap': PlugZap,
	'upload': Upload,
	'film': Film,
	'plus': Plus,
	'audio-waveform': AudioWaveform,
	'video': Video,
	'captions': Captions,
	'scan-line': ScanLine,
	'sliders-horizontal': SlidersHorizontal,
	'mic': Mic,
	'clapperboard': Clapperboard,
	'search': Search,
	'eye': Eye,
	'eye-off': EyeOff,
	'lock': Lock,
	'volume-2': Volume2,
	'volume-x': VolumeX,
	'clock': Clock,
	'loader': Loader,
	'git-pull-request-arrow': GitPullRequestArrow,
	'check': Check,
	'crop': Crop,
	'list-plus': ListPlus,
	'corner-down-left': CornerDownLeft,
	'hand': Hand,
	'file-search': FileSearch,
	'file-plus': FilePlus,
	'history': History,
	'undo': Undo2,
	'redo': Redo2,
	'rotate-ccw': RotateCcw,
	'folder-open': FolderOpen,
	'save': Save,
	'zoom-in': ZoomIn,
	'zoom-out': ZoomOut,
	'trash': Trash2,
	'copy': Copy,
	'chevron-down': ChevronDown,
	'image': Image,
	'x': X,
	'download': Download,
	'refresh-cw': RefreshCw,
	'external-link': ExternalLink,
	'alert-triangle': TriangleAlert,
	'lightbulb': Lightbulb,
	'bell': Bell,
	'settings': Settings
};

export type IconName = keyof typeof icons;
