import type { Icon as LucideIcon } from '@lucide/svelte';
import {
	MousePointer2,
	Scissors,
	Bookmark,
	Magnet,
	SkipBack,
	SkipForward,
	Play,
	Pause,
	Plug,
	PlugZap,
	Upload,
	Film,
	Plus,
	AudioWaveform,
	Video,
	Captions,
	ScanLine,
	SlidersHorizontal,
	Clapperboard,
	Search,
	Eye,
	Lock,
	Volume2,
	Clock,
	Loader,
	GitPullRequestArrow,
	Check,
	ListPlus,
	CornerDownLeft,
	Hand,
	FileSearch,
	History,
	Undo2,
	Redo2,
	RotateCcw
} from '@lucide/svelte';

/* Keyed by the names the design uses (kebab or PascalCase, as authored). */
export const icons: Record<string, typeof LucideIcon> = {
	'MousePointer2': MousePointer2,
	'Scissors': Scissors,
	'Bookmark': Bookmark,
	'magnet': Magnet,
	'skip-back': SkipBack,
	'skip-forward': SkipForward,
	'play': Play,
	'pause': Pause,
	'plug': Plug,
	'plug-zap': PlugZap,
	'upload': Upload,
	'film': Film,
	'plus': Plus,
	'audio-waveform': AudioWaveform,
	'video': Video,
	'captions': Captions,
	'scan-line': ScanLine,
	'sliders-horizontal': SlidersHorizontal,
	'clapperboard': Clapperboard,
	'search': Search,
	'eye': Eye,
	'lock': Lock,
	'volume-2': Volume2,
	'clock': Clock,
	'loader': Loader,
	'git-pull-request-arrow': GitPullRequestArrow,
	'check': Check,
	'list-plus': ListPlus,
	'corner-down-left': CornerDownLeft,
	'hand': Hand,
	'file-search': FileSearch,
	'history': History,
	'undo': Undo2,
	'redo': Redo2,
	'rotate-ccw': RotateCcw
};

export type IconName = keyof typeof icons;
